### ISSUE TITLE
Renaming the database names makes crossdb queries very brittle

### ISSUE THREAD

**Issue by fgregg** [simonw/datasette-hashed-urls#10]
Before, this crossdb query would work

https://labordata.bunkum.us/_memory?sql=select+*+from+%5Bf7%5D.f7+inner+join+%5Bnlrb%5D.filing+on+1+%3D+1+limit+10%3B

but it doesn't now, because this plugin renames the database names, so you have to have the hashed names into the crossdb query

https://labordata.bunkum.us/_memory?sql=select+*+from+%5Bf7-8035c93%5D.f7+inner+join+%5Bnlrb-0d2bab9%5D.filing+on+1+%3D+1+limit+10%3B

but that is very brittle. if one of the db updates, then that query won't work anymore.

**Comment by simonw** [comment]
Oh no! That's a really gnarly edge-case, thanks for spotting that one. Definitely need to fix this.

I think this can be addressed by having the code that sets up `_memory` know to use the original alias for the database.

That might require a supporting change to Datasette core - a way of separating the concept of the path that the database is served on from the name that is used as an alias.

**Comment by fgregg** [comment]
if you did that separation, then the other two issues would be easy to address to (have the db name and link text use the alias)

**Comment by simonw** [comment]
This is fixed by b7ec37014d34de5768933577337244090a71d4e1 but needs a test.

**Comment by simonw** [comment]
OK, this is working - here's a demo of the fix: https://datasette-hashed-urls-preview.vercel.app/_memory?sql=select+*+from+fixtures.facetable+union+all+select+*+from+fixtures2.facetable

**Comment by simonw** [comment]
@fgregg you can preview this yourself by installing the new Datasette alpha:

    pip install datasette==0.61a0

And then installing the latest commit of this plugin like so:

    datasette install https://github.com/simonw/datasette-hashed-urls/archive/be554804c0a68e21c3cd52e9aebb287d10d2179e.zip

**Comment by fgregg** [comment]
thanks so much, @simonw. 

https://labordata.bunkum.us/_memory?sql=select+*+from+%5Bf7%5D.f7+inner+join+%5Bnlrb%5D.filing+on+1+%3D+1+limit+10%3B

now works again!
