### ISSUE TITLE
json query do db name not getting appropriately redirected.

### ISSUE THREAD

**Issue by fgregg** [simonw/datasette-hashed-urls#12]
this query: https://labordata.bunkum.us/nlrb.json?sql=select+'hello+world'

should get redirected to the most recent nlrb hased url, instead it 404s and says db not found.

**Comment by simonw** [comment]
Even after fixing #13 I'm still getting this bug.

**Comment by simonw** [comment]
Actually no, my mistake: the bug appears to be fixed now. I'll add a test.

**Comment by simonw** [comment]
There was a new bug. I think I found the fix.
