### ISSUE TITLE
queries failing on hashed db

### ISSUE THREAD

**Issue by fgregg** [simonw/datasette-hashed-urls#13]
go to a database page like https://labordata.bunkum.us/f7

![Screenshot 2022-03-20 at 06-38-12 f7](https://user-images.githubusercontent.com/536941/159158479-23c277eb-113b-45ec-84c2-41a6043fe362.png)

enter any query into the SQL query box and run sql which takes you to a url like https://labordata.bunkum.us/f7-8035c93?sql=select+*+from+f7

get a 500 error

![Screenshot 2022-03-20 at 06-38-27 Error 500](https://user-images.githubusercontent.com/536941/159158483-4e15370a-8a5c-4994-8ddf-5ab730c1539b.png)

**Comment by fgregg** [comment]
note: the individual table pages work, but if you try an arbitrary query on them you get the same 500 error

**Comment by fgregg** [comment]
i'm going to revert this change on labordata.bunkum.us, but the same behavior is visible here: https://datasette-hashed-urls-preview.vercel.app/fixtures-09f8f95?sql=select+*+from+%5B123_starts_with_digits%5D

**Comment by simonw** [comment]
Here's the trace:
```
  File "/Users/simon/.local/share/virtualenvs/datasette-hashed-urls-ssI2fO50/lib/python3.10/site-packages/datasette/views/database.py", line 54, in data
    return await QueryView(self.ds).data(
  File "/Users/simon/.local/share/virtualenvs/datasette-hashed-urls-ssI2fO50/lib/python3.10/site-packages/datasette/views/database.py", line 232, in data
    self.ds.get_database(database), sql
  File "/Users/simon/.local/share/virtualenvs/datasette-hashed-urls-ssI2fO50/lib/python3.10/site-packages/datasette/app.py", line 401, in get_database
    return self.databases[name]
KeyError: 'fixtures-aa7318b'
```
It looks like this is a Datasette bug, which is frustrating because I just shipped Datasette 0.61 five minutes ago!

**Comment by simonw** [comment]
Here's a test which fails against Datasette 0.61 but passes against the latest commit to Datasette `main`:

```diff
diff --git a/tests/test_hashed_urls.py b/tests/test_hashed_urls.py
index 096af59..150298a 100644
--- a/tests/test_hashed_urls.py
+++ b/tests/test_hashed_urls.py
@@ -34,9 +34,11 @@ async def test_immutable_database_has_new_route_on_startup(ds):
     (
         ("/", False),
         ("/this-is-mutable", False),
+        ("/this-is-mutable?sql=select+1", False),
         ("/this-is-mutable/t", False),
         ("/this-is-mutable/t/1", False),
         ("/this-is-immutable", True),
+        ("/this-is-immutable?sql=select+1", True),
         ("/this-is-immutable/t", True),
         ("/this-is-immutable/t?id=1", True),
         ("/this-is-immutable/t/1", True),
@@ -55,6 +57,9 @@ async def test_paths_with_no_hash_redirect(ds, path, should_redirect):
             "/this-is-immutable", "/this-is-immutable-{}".format(immutable_hash)
         )
         assert response.headers["location"] == expected_path
+        # Fetch that one too and make sure it is 200
+        second_response = await ds.client.get(response.headers["location"])
+        assert second_response.status_code == 200
     else:
         assert response.status_code == 200
 ```

**Comment by simonw** [comment]
Re-opening because I need to depend on Datasette 0.61.1.
