### ISSUE TITLE
json query to db is missing CORS headers but query to _memory has them

### ISSUE THREAD

**Issue by fgregg** [simonw/datasette-hashed-urls#14]
this request to the _memory endpoint returns a response with the right CORS headers: 

https://labordata.bunkum.us/_memory.json?sql=select+%27hello%27%3B

but this query to a database endpoint, does not.

https://labordata.bunkum.us/nlrb.json?sql=select+%27hello%27%3B

That endpoint should redirect to a hashed url like, 

https://labordata.bunkum.us/nlrb-8eeb4a3.json?sql=select+%27hello%27%3B

which *does* have the right CORS headers. I **think** the issue is that the 302 response does not have the right CORS headers.

This is preventing an Observable page like https://observablehq.com/@fgregg/petitions-for-representation-certification-elections-fi to fetch the data.

**Comment by simonw** [comment]
Yup:
```
~ % curl -i 'https://labordata.bunkum.us/_memory.json?sql=select+%27hello%27%3B'
HTTP/2 200 
date: Thu, 24 Mar 2022 03:15:34 GMT
content-type: application/json; charset=utf-8
cache-control: max-age=5
referrer-policy: no-referrer
access-control-allow-origin: *
access-control-allow-headers: Authorization
access-control-expose-headers: Link
```
Compared to:
```
{"ok": true, "database": "_memory", "query_name": null, "rows": [["hello"]], "truncated": false, "columns": ["'hello'"], "query": {"sql": "select 'hello';", "params": {}}, "error": null, "private": false, "allow_execute_sql": true, "query_ms": 1.1404910001147073}%                                                                                                                                      ~ % curl -i 'https://labordata.bunkum.us/nlrb.json?sql=select+%27hello%27%3B'
HTTP/2 302 
date: Thu, 24 Mar 2022 03:16:09 GMT
content-type: text/html
location: /nlrb-8eeb4a3.json?sql=select+'hello'%3B
x-cloud-trace-context: 85c98763279631b912ddf6c8526bc299;o=1
cf-cache-status: BYPASS
```
