### ISSUE TITLE
On database page, have the database name without the -HASH suffix

### ISSUE THREAD

**Issue by fgregg** [simonw/datasette-hashed-urls#9]
On database tables, it would good to have the database name not have a -HASH prefix.

![Screenshot 2022-03-19 at 09-49-52 f7-8035c93](https://user-images.githubusercontent.com/536941/159123741-7ebc65f7-a04b-4241-b9ad-6a4d927d6cf3.png)

**Comment by fgregg** [comment]
the best design for how to accommodate this is not obvious. 

it seems like you don't want to handle this is an a custom template for this plugin

the alternative would be for all database objects to have an attribute like "display_name" and have that be used in upstream templates. but, that might be adding to much cruft if the only use case is this one plugin.

**Comment by simonw** [comment]
That title in the template looks like this:

https://github.com/simonw/datasette/blob/764738dfcb16cd98b0987d443f59d5baa9d3c332/datasette/templates/database.html#L23

```html
    <h1>{{ metadata.title or database }}{% if private %} 🔒{% endif %}</h1>
```
So one option would be for this plugin to use the `get_metadata` hook at https://docs.datasette.io/en/stable/plugin_hooks.html#get-metadata-datasette-key-database-table to customize that value - but only if it's not already customized by the `metadata.json` for the instance.

Worth investigating as an option.
